const {test}=require('node:test');
const assert=require('node:assert/strict');
const P=require('../policy.js');
const state=()=>({configured:true,initialBalance:1005,maximumSpend:1000,events:[]});
const proof=()=>({variant:'draft-a',candidate:1,stage:'generate',balance:1005,quote:65});
test('read a unique integer price and formatted balance',()=>{assert.equal(P.number('Generate 65'),65);assert.equal(P.number('1,005'),1005);});
test('reject ambiguous versions, missing prices, negative values and fractional credits',()=>{for(const s of ['v3 Generate 65','Generate','65.5','-65'])assert.throws(()=>P.number(s));});
test('budget permits a 65 credit stage and exact final spend',()=>{assert.equal(P.gate(state(),proof()).remaining,935);assert.equal(P.gate(state(),{...proof(),quote:1000}).remaining,0);});
test('preserve minimum balance and reject insufficient or excessive quote',()=>{for(const p of [{...proof(),quote:1001},{...proof(),balance:64},{...proof(),quote:0},{...proof(),quote:-1}])assert.throws(()=>P.gate(state(),p));});
test('other account spend counts conservatively',()=>{assert.throws(()=>P.gate(state(),{...proof(),balance:60,quote:65}));assert.equal(P.gate(state(),{...proof(),balance:505}).remaining,435);});
test('any uncertain or in-flight stage blocks every other paid stage',()=>{for(const status of ['uncertain','submitting'])assert.throws(()=>P.gate({...state(),events:[{key:P.key({...proof(),variant:'draft-b',stage:'texture'}),quote:100,status}]},proof()));});
test('accepted stage cannot be resubmitted after restart',()=>{assert.throws(()=>P.gate({...state(),events:[{key:P.key(proof()),quote:65,status:'accepted'}]},proof()));});
test('intentional iteration uses a new candidate; quoted stage costs accumulate',()=>{const s={...state(),events:[{key:P.key(proof()),quote:65,status:'accepted'}]};assert.equal(P.gate(s,{...proof(),candidate:2}).remaining,870);});
test('definitely cancelled-before-click claim can be tried later',()=>{const s={...state(),events:[{key:P.key(proof()),quote:65,status:'cancelled'}]};assert.equal(P.gate(s,proof()).remaining,935);});
test('observed expense high-water mark survives later balance increases',()=>{const s={...state(),observedSpendHighWater:950};assert.throws(()=>P.gate(s,proof()));});
test('restrict stages, styles and candidate identity',()=>{for(const p of [{...proof(),variant:''},{...proof(),candidate:0},{...proof(),stage:'recharge'}])assert.throws(()=>P.gate(state(),p));});
test('no default budget; unconfigured task can never pay',()=>{assert.throws(()=>P.gate({configured:false,events:[]},proof()));});
test('arbitrary prop/human/animal variant names work without a type template',()=>{for(const variant of ['石桥','人物造型','quadruped','方案:1'])assert.equal(P.gate(state(),{...proof(),variant}).remaining,935);});
test('task config requires explicit authorization and valid budget',()=>{const c={schema:1,id:'sample',name:'通用模型任务',initialBalance:500,maximumSpend:100,variants:['A','B'],authorization:'明确授权'};assert.equal(P.task(c).maximumSpend,100);for(const change of [{authorization:''},{maximumSpend:501},{variants:['A','A']},{id:'../folder'}])assert.throws(()=>P.task({...c,...change}));});
